# Greek Letters

The following tables present the names of Greek letters and selected symbols commonly used in engineering courses, ensuring precise reference and avoiding reliance on informal descriptors such as “squiggle.”

| Lower Case | Upper Case | Name    |
|:----------:|:----------:|:--------|
|  $\alpha$  |     A      | alpha   |
|  $\beta$   |     B      | beta    |
|  $\gamma$  |  $\Gamma$  | gamma   |
|  $\delta$  |  $\Delta$  | delta   |
| $\epsilon$ |     E      | epsilon |
|  $\zeta$   |     Z      | zeta    |
|   $\eta$   |     E      | eta     |
|  $\theta$  |  $\Theta$  | theta   |
|  $\iota$   |     I      | iota    |
|  $\kappa$  |     K      | kappa   |
| $\lambda$  | $\Lambda$  | lambda  |
|   $\mu$    |     M      | mu      |
|   $\nu$    |     N      | nu      |
|   $\xi$    |   $\Xi$    | xi      |
| $\omicron$ |     O      | omicron |
|   $\pi$    |   $\Pi$    | pi      |
|   $\rho$   |     P      | rho     |
|  $\sigma$  |  $\Sigma$  | sigma   |
|   $\tau$   |     T      | tau     |
| $\upsilon$ | $\Upsilon$ | upsilon |
|   $\phi$   |   $\Phi$   | phi     |
|   $\chi$   |     X      | chi     |
|   $\psi$   |   $\Psi$   | psi     |
|  $\omega$  |  $\Omega$  | omega   |

: Greek letters.

| Symbol | Name | Use | Course |
|:---------------:|:----------------|:----------------|:--------------------|
| $\Delta$ | Delta | Change | Thermodynamics |
| $\Delta$ | Delta | Displacement | Naval Architecture |
| $\nabla$ | Nabla | Volume | Naval Architecture |
| $\Sigma$ | Sigma | Sum | Thermodynamics, Naval Architecture, Applied Mechanics |
| $\sigma$ | Sigma | Stress | Thermodynamics, Applied Mechanics |
| $\epsilon$ | Epsilon | Modulus of elasticity | Thermodynamics, Applied Mechanics |
| $\eta$ | Eta | Efficiency | Thermodynamics |
| $\mu$ | Mu | Friction | Thermodynamics, Applied Mechanics |
| $\omega$ | Omega | Angular velocity | Thermodynamics, Applied Mechanics |
| $\rho$ | Rho | Density | Thermodynamics, Naval Architecture |
| $\tau$ | Tau | Torque | Thermodynamics, Applied Mechanics |

: Commonly used symbols in engineering courses.